Web Page Clone of Newsweek we page
abdelp/using-bootstrap pull request #2
Opened 2020-02-07 20:14 UTC by abdelp

Responsive design of Newsweek webpage

Based on the Odin Project Requirements specified here: https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap

use of grids with bootstrap framework v4.4.1

2020-02-07 20:26 UTC, pelzolga123 commented
### Hi Abdel! I am marking this review request as invalid, because your linter is not setup for this repository. 
Please kindly setup linter and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-07 20:51 UTC, abdelp commented
Enabled linter in the repository

2020-02-07 20:56 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-02-07 21:29 UTC, addod19 requested changes
## Status: Require changes 🔴 

Hi @abdelp, you did a great job enabling linter for your repo. 👍 However, there are some few recommendations. Find comment below:
- Kindly fix the warning
![sl](https://user-images.githubusercontent.com/46388113/74065800-968b2680-49ed-11ea-9f24-ac67c2c9ea1d.PNG)
 returned by [HTML markup](https://validator.w3.org/)
- ```Tablet mode``` Currently this is how it looks **(1 column)**
![new1](https://user-images.githubusercontent.com/46388113/74066127-6abc7080-49ee-11ea-8208-1908d2147e70.PNG) It should be like this **(2 columns)**
![onew1](https://user-images.githubusercontent.com/46388113/74066167-80319a80-49ee-11ea-81df-e6a29f3c319a.PNG)
- Currently,  this part looks like this
![not](https://user-images.githubusercontent.com/46388113/74066408-efa78a00-49ee-11ea-9148-4007da757c14.PNG)
It should be this
![an](https://user-images.githubusercontent.com/46388113/74066459-077f0e00-49ef-11ea-8d7a-be613c3a433d.PNG)
- Kindly make the following changes and aligns on breakpoints:
Featured Stories, Top story, Opinion, Latest news, more stories, In the magazine, editors pick, Featured slidshows
![co](https://user-images.githubusercontent.com/46388113/74067130-6bee9d00-49f0-11ea-9d19-6c605e765aab.PNG)
- There is a horizontal scroll. 

Kindly make these changes and submit another code review 🙂 
Happy coding 💻 
Daniel Larbi Addo

2020-02-07 21:29 UTC, addod19 commented on assets/stylesheets/style.css
> +.footer {
I suggest you give these classes a ```width:100%```. To solve the horizontal scroll we get on tablet and mobile screen sizes

2020-02-07 22:36 UTC, abdelp commented
Removed warning from the linter
Updated the alignment for medium sizes devices on top history
fixed the horizontal scroll
Updated alignment for sections

2020-02-07 22:49 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2020-02-07 23:14 UTC, Anna-Myzukina commented
## Hi @abdelp !
### Nice job! Project looks! :+1: 

### But your project needs a few changes before it can be approved.
#### Implementation details


*  It adds [viewport metatag](https://getbootstrap.com/docs/4.3/getting-started/introduction/#responsive-meta-tag) 
![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_requirement.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap)
*  It uses Bootstrap Css classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) 
![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/)

### Main content

**It changes with RWD breakpoints** ([link to page](https://www.newsweek.com/))

* Kindly recommended checking all parts of your project, it still has a big difference:

#### Your version
![us1](https://user-images.githubusercontent.com/26605804/74072548-d06d2480-4a0f-11ea-990c-3bc97cc67728.png)
#### Original
![us](https://user-images.githubusercontent.com/26605804/74072538-ccd99d80-4a0f-11ea-8bcb-0e4efa6fd89f.png)

#### Your version
![subscr](https://user-images.githubusercontent.com/26605804/74072552-d400ab80-4a0f-11ea-8eac-3cd953292970.png)

#### Original
![subs](https://user-images.githubusercontent.com/26605804/74072566-de22aa00-4a0f-11ea-8ace-f52bd77d96e3.png)
![newsl](https://user-images.githubusercontent.com/26605804/74072578-e24ec780-4a0f-11ea-8fda-cd925935a9f1.png)


*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

2020-02-07 23:14 UTC, Anna-Myzukina requested changes
The project still needs changes

2020-02-11 20:22 UTC, nikasulo approved these changes
# Your hard work has paid off! :rocket: 
This is really great work @abdelp :handshake: Please merge this and be on your way :smile:. See you at the top :medal_military:  

#### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-11 20:26 UTC, merged

2020-02-11 20:27 UTC, abdelp commented
Thank you very much, guys!